const PLATFORM_CONFIG = {
  serviceArea: "College Gate",
  deliveryFeeBDT: 50
};

const restaurantsData = [
  {
    id: "rest-001",
    name: "Bismillah Mini Chinese and Fast Food",
    image: "assets/restaurants/bismillah.png",
    category: "Fast Food & Snacks",
    location: "College Gate",
    description: "Open:10 AM-10 PM.",
    rating: 3.9,
    menu: [
      { id: "item-101", name: "চিকেন ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-102", name: "ক্রিস্পি চিকেন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-103", name: "চিকেন উইংস (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-104", name: "ফ্রাইড রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-105", name: "চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-106", name: "স্পেশাল চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-107", name: "স্পেশাল ফ্রাইড রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 400, available: true },
      { id: "item-108", name: "বিফ রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-109", name: "প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-110", name: "চিকেন & প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-111", name: "চিকেন সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-112", name: "বিফ সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-113", name: "বিফ কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-114", name: "চিকেন কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-115", name: "চিকেন ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-116", name: "ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-117", name: "বিফ চিলি ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-118", name: "চিকেন পিজ্জা ৬\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 260, available: true },
      { id: "item-119", name: "চিকেন পিজ্জা ৯\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-120", name: "বিফ পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-121", name: "প্রন পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-122", name: "চাওমিন (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-123", name: "থাই নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-124", name: "নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-125", name: "চিকেন নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-126", name: "স্পেশাল নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-127", name: "থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-128", name: "চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-129", name: "চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-130", name: "চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-131", name: "ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-132", name: "স্প্রিং রোল (৮ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-133", name: "চিকেন অনথন (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-134", name: "ক্রিস্পি বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-135", name: "চিকেন চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-136", name: "বিফ সাব চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-137", name: "চিকেন বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-138", name: "বিফ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-139", name: "বিফ চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-140", name: "চিকেন লেগ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-141", name: "চিকেন স্পেশাল বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-142", name: "নাগা বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-143", name: "সাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-144", name: "সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-145", name: "বিফ সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-146", name: "ক্লাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-147", name: "চিকেন স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-148", name: "চিকেন ললিপপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-149", name: "চিকেন ড্রাম স্টিক (২ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-150", name: "পাস্তা (রেড সস) (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-151", name: "পাস্তা উইথ চিজ (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-152", name: "চিংড়ি ফ্রাই (১০ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-153", name: "আমেরিকান চপসি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 380, available: true },
      { id: "item-154", name: "চিকেন চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-155", name: "প্রন চিলি অনিয়ন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-156", name: "বিফ চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-157", name: "চিকেন সাব বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-158", name: "চিকেন মিট বল (৪ স্টিক)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-159", name: "ফ্রেঞ্চ ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-160", name: "মিল্ক শেক", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-161", name: "মুঠি কাবাব", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-162", name: "চিকেন চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-163", name: "বিফ চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-164", name: "চিকেন নাগেট (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-165", name: "চিকেন ক্যাসোনাট সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-166", name: "গ্রিন সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-167", name: "ফ্রেশ জুস (সিজনাল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-168", name: "কোল্ড কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-169", name: "লাচ্ছি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-170", name: "কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-171", name: "পানি (৫০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },
      { id: "item-172", name: "কোল্ড ড্রিংস (ওয়ান টাইম গ্লাস ২০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },

      { id: "item-173", name: "প্যাকেজ ০১: ফ্রাইড রাইস + ভেজিটেবল কারি + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০১ (১:১)", price: 220, available: true },
      { id: "item-174", name: "প্যাকেজ ০২: ফ্রাইড রাইস + চিকেন কারি + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০২ (১:১)", price: 270, available: true },
      { id: "item-175", name: "প্যাকেজ ০৩: চিকেন রাইস + চিকেন ফ্রাই (৪ পিস) + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৩ (১:১)", price: 290, available: true },
      { id: "item-176", name: "প্যাকেজ ০৪: ফ্রাইড রাইস + বিফ চিলি ফ্রাই + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৪ (১:১)", price: 380, available: true },
      { id: "item-177", name: "প্যাকেজ ০৫: চিকেন রাইস + মিনি চিকেন + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৫ (১:১)", price: 250, available: true },
      { id: "item-178", name: "প্যাকেজ ০৬: চিকেন রাইস + চিকেন ফ্রাই + ভেজিটেবল + থাই স্যুপ/চিকেন স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৬ (১:১)", price: 380, available: true },
      { id: "item-179", name: "প্যাকেজ ০৭: থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-180", name: "প্যাকেজ ০৭: চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-181", name: "প্যাকেজ ০৭: ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-182", name: "প্যাকেজ ০৭: চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-183", name: "প্যাকেজ ০৭: চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-184", name: "প্যাকেজ ০৮: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + থাই স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৮ (১:২)", price: 720, available: true },
      { id: "item-185", name: "প্যাকেজ ০৯: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + কোক + থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৯ (১:৪)", price: 1600, available: true },
      { id: "item-186", name: "প্যাকেজ ১০: চিজ বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১০ (১:১)", price: 300, available: true },
      { id: "item-187", name: "প্যাকেজ ১১: চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১১ (১:১)", price: 180, available: true },
      { id: "item-188", name: "প্যাকেজ ১২: বিফ/চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১২ (১:১)", price: 280, available: true },
      { id: "item-189", name: "প্যাকেজ ১৩: চিকেন চাওমিন + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৩ (১:১)", price: 290, available: true },
      { id: "item-190", name: "প্যাকেজ ১৪: স্যুপ + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৪ (১:১)", price: 250, available: true },
      { id: "item-191", name: "প্যাকেজ ১৫: ফ্রাইড রাইস + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৫ (১:১)", price: 220, available: true },
      { id: "item-192", name: "প্যাকেজ ১৬: থাই স্যুপ + ওয়ানটন (০২ পিস) + চিকেন ফ্রাই (০২ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৬ (১:১)", price: 280, available: true }
    ]
  },

  {
    id: "rest-002",
    name: "King's Delicious Food",
    image: "assets/restaurants/kings.jpg",
    category: "Fast Food & Snacks",
    location: "College Gate",
    description: "Open:10 AM-10 PM.",
    rating: 4.1,
    menu: [
      { id: "item-101", name: "চিকেন ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-102", name: "ক্রিস্পি চিকেন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-103", name: "চিকেন উইংস (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-104", name: "ফ্রাইড রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-105", name: "চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-106", name: "স্পেশাল চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-107", name: "স্পেশাল ফ্রাইড রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 400, available: true },
      { id: "item-108", name: "বিফ রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-109", name: "প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-110", name: "চিকেন & প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-111", name: "চিকেন সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-112", name: "বিফ সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-113", name: "বিফ কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-114", name: "চিকেন কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-115", name: "চিকেন ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-116", name: "ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-117", name: "বিফ চিলি ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-118", name: "চিকেন পিজ্জা ৬\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 260, available: true },
      { id: "item-119", name: "চিকেন পিজ্জা ৯\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-120", name: "বিফ পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-121", name: "প্রন পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-122", name: "চাওমিন (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-123", name: "থাই নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-124", name: "নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-125", name: "চিকেন নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-126", name: "স্পেশাল নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-127", name: "থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-128", name: "চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-129", name: "চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-130", name: "চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-131", name: "ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-132", name: "স্প্রিং রোল (৮ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-133", name: "চিকেন অনথন (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-134", name: "ক্রিস্পি বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-135", name: "চিকেন চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-136", name: "বিফ সাব চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-137", name: "চিকেন বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-138", name: "বিফ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-139", name: "বিফ চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-140", name: "চিকেন লেগ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-141", name: "চিকেন স্পেশাল বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-142", name: "নাগা বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-143", name: "সাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-144", name: "সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-145", name: "বিফ সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-146", name: "ক্লাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-147", name: "চিকেন স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-148", name: "চিকেন ললিপপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-149", name: "চিকেন ড্রাম স্টিক (২ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-150", name: "পাস্তা (রেড সস) (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-151", name: "পাস্তা উইথ চিজ (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-152", name: "চিংড়ি ফ্রাই (১০ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-153", name: "আমেরিকান চপসি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 380, available: true },
      { id: "item-154", name: "চিকেন চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-155", name: "প্রন চিলি অনিয়ন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-156", name: "বিফ চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-157", name: "চিকেন সাব বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-158", name: "চিকেন মিট বল (৪ স্টিক)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-159", name: "ফ্রেঞ্চ ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-160", name: "মিল্ক শেক", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-161", name: "মুঠি কাবাব", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-162", name: "চিকেন চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-163", name: "বিফ চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-164", name: "চিকেন নাগেট (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-165", name: "চিকেন ক্যাসোনাট সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-166", name: "গ্রিন সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-167", name: "ফ্রেশ জুস (সিজনাল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-168", name: "কোল্ড কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-169", name: "লাচ্ছি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-170", name: "কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-171", name: "পানি (৫০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },
      { id: "item-172", name: "কোল্ড ড্রিংস (ওয়ান টাইম গ্লাস ২০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },

      { id: "item-173", name: "প্যাকেজ ০১: ফ্রাইড রাইস + ভেজিটেবল কারি + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০১ (১:১)", price: 220, available: true },
      { id: "item-174", name: "প্যাকেজ ০২: ফ্রাইড রাইস + চিকেন কারি + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০২ (১:১)", price: 270, available: true },
      { id: "item-175", name: "প্যাকেজ ০৩: চিকেন রাইস + চিকেন ফ্রাই (৪ পিস) + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৩ (১:১)", price: 290, available: true },
      { id: "item-176", name: "প্যাকেজ ০৪: ফ্রাইড রাইস + বিফ চিলি ফ্রাই + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৪ (১:১)", price: 380, available: true },
      { id: "item-177", name: "প্যাকেজ ০৫: চিকেন রাইস + মিনি চিকেন + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৫ (১:১)", price: 250, available: true },
      { id: "item-178", name: "প্যাকেজ ০৬: চিকেন রাইস + চিকেন ফ্রাই + ভেজিটেবল + থাই স্যুপ/চিকেন স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৬ (১:১)", price: 380, available: true },
      { id: "item-179", name: "প্যাকেজ ০৭: থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-180", name: "প্যাকেজ ০৭: চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-181", name: "প্যাকেজ ০৭: ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-182", name: "প্যাকেজ ০৭: চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-183", name: "প্যাকেজ ০৭: চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-184", name: "প্যাকেজ ০৮: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + থাই স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৮ (১:২)", price: 720, available: true },
      { id: "item-185", name: "প্যাকেজ ০৯: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + কোক + থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৯ (১:৪)", price: 1600, available: true },
      { id: "item-186", name: "প্যাকেজ ১০: চিজ বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১০ (১:১)", price: 300, available: true },
      { id: "item-187", name: "প্যাকেজ ১১: চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১১ (১:১)", price: 180, available: true },
      { id: "item-188", name: "প্যাকেজ ১২: বিফ/চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১২ (১:১)", price: 280, available: true },
      { id: "item-189", name: "প্যাকেজ ১৩: চিকেন চাওমিন + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৩ (১:১)", price: 290, available: true },
      { id: "item-190", name: "প্যাকেজ ১৪: স্যুপ + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৪ (১:১)", price: 250, available: true },
      { id: "item-191", name: "প্যাকেজ ১৫: ফ্রাইড রাইস + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৫ (১:১)", price: 220, available: true },
      { id: "item-192", name: "প্যাকেজ ১৬: থাই স্যুপ + ওয়ানটন (০২ পিস) + চিকেন ফ্রাই (০২ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৬ (১:১)", price: 280, available: true }
    ]
  },

  {
    id: "rest-003",
    name: "Rustic Lounge-Tongi",
    image: "assets/restaurants/Rustic.jpg",
    category: "Fast Food & Snacks",
    location: "College Gate",
    description: "Open:10 AM-10 PM.",
    rating: 3.9,
    menu: [
      { id: "item-101", name: "চিকেন ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-102", name: "ক্রিস্পি চিকেন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-103", name: "চিকেন উইংস (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-104", name: "ফ্রাইড রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-105", name: "চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-106", name: "স্পেশাল চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-107", name: "স্পেশাল ফ্রাইড রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 400, available: true },
      { id: "item-108", name: "বিফ রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-109", name: "প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-110", name: "চিকেন & প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-111", name: "চিকেন সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-112", name: "বিফ সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-113", name: "বিফ কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-114", name: "চিকেন কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-115", name: "চিকেন ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-116", name: "ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-117", name: "বিফ চিলি ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-118", name: "চিকেন পিজ্জা ৬\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 260, available: true },
      { id: "item-119", name: "চিকেন পিজ্জা ৯\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-120", name: "বিফ পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-121", name: "প্রন পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-122", name: "চাওমিন (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-123", name: "থাই নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-124", name: "নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-125", name: "চিকেন নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-126", name: "স্পেশাল নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-127", name: "থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-128", name: "চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-129", name: "চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-130", name: "চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-131", name: "ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-132", name: "স্প্রিং রোল (৮ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-133", name: "চিকেন অনথন (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-134", name: "ক্রিস্পি বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-135", name: "চিকেন চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-136", name: "বিফ সাব চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-137", name: "চিকেন বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-138", name: "বিফ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-139", name: "বিফ চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-140", name: "চিকেন লেগ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-141", name: "চিকেন স্পেশাল বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-142", name: "নাগা বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-143", name: "সাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-144", name: "সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-145", name: "বিফ সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-146", name: "ক্লাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-147", name: "চিকেন স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-148", name: "চিকেন ললিপপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-149", name: "চিকেন ড্রাম স্টিক (২ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-150", name: "পাস্তা (রেড সস) (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-151", name: "পাস্তা উইথ চিজ (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-152", name: "চিংড়ি ফ্রাই (১০ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-153", name: "আমেরিকান চপসি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 380, available: true },
      { id: "item-154", name: "চিকেন চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-155", name: "প্রন চিলি অনিয়ন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-156", name: "বিফ চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-157", name: "চিকেন সাব বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-158", name: "চিকেন মিট বল (৪ স্টিক)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-159", name: "ফ্রেঞ্চ ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-160", name: "মিল্ক শেক", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-161", name: "মুঠি কাবাব", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-162", name: "চিকেন চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-163", name: "বিফ চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-164", name: "চিকেন নাগেট (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-165", name: "চিকেন ক্যাসোনাট সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-166", name: "গ্রিন সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-167", name: "ফ্রেশ জুস (সিজনাল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-168", name: "কোল্ড কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-169", name: "লাচ্ছি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-170", name: "কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-171", name: "পানি (৫০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },
      { id: "item-172", name: "কোল্ড ড্রিংস (ওয়ান টাইম গ্লাস ২০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },

      { id: "item-173", name: "প্যাকেজ ০১: ফ্রাইড রাইস + ভেজিটেবল কারি + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০১ (১:১)", price: 220, available: true },
      { id: "item-174", name: "প্যাকেজ ০২: ফ্রাইড রাইস + চিকেন কারি + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০২ (১:১)", price: 270, available: true },
      { id: "item-175", name: "প্যাকেজ ০৩: চিকেন রাইস + চিকেন ফ্রাই (৪ পিস) + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৩ (১:১)", price: 290, available: true },
      { id: "item-176", name: "প্যাকেজ ০৪: ফ্রাইড রাইস + বিফ চিলি ফ্রাই + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৪ (১:১)", price: 380, available: true },
      { id: "item-177", name: "প্যাকেজ ০৫: চিকেন রাইস + মিনি চিকেন + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৫ (১:১)", price: 250, available: true },
      { id: "item-178", name: "প্যাকেজ ০৬: চিকেন রাইস + চিকেন ফ্রাই + ভেজিটেবল + থাই স্যুপ/চিকেন স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৬ (১:১)", price: 380, available: true },
      { id: "item-179", name: "প্যাকেজ ০৭: থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-180", name: "প্যাকেজ ০৭: চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-181", name: "প্যাকেজ ০৭: ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-182", name: "প্যাকেজ ০৭: চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-183", name: "প্যাকেজ ০৭: চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-184", name: "প্যাকেজ ০৮: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + থাই স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৮ (১:২)", price: 720, available: true },
      { id: "item-185", name: "প্যাকেজ ০৯: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + কোক + থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৯ (১:৪)", price: 1600, available: true },
      { id: "item-186", name: "প্যাকেজ ১০: চিজ বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১০ (১:১)", price: 300, available: true },
      { id: "item-187", name: "প্যাকেজ ১১: চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১১ (১:১)", price: 180, available: true },
      { id: "item-188", name: "প্যাকেজ ১২: বিফ/চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১২ (১:১)", price: 280, available: true },
      { id: "item-189", name: "প্যাকেজ ১৩: চিকেন চাওমিন + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৩ (১:১)", price: 290, available: true },
      { id: "item-190", name: "প্যাকেজ ১৪: স্যুপ + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৪ (১:১)", price: 250, available: true },
      { id: "item-191", name: "প্যাকেজ ১৫: ফ্রাইড রাইস + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৫ (১:১)", price: 220, available: true },
      { id: "item-192", name: "প্যাকেজ ১৬: থাই স্যুপ + ওয়ানটন (০২ পিস) + চিকেন ফ্রাই (০২ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৬ (১:১)", price: 280, available: true }
    ]
  }, 

  {
    id: "rest-004",
    name: "🍨Yumi🍟",
    image: "assets/restaurants/yumi.jpg",
    category: "Fast Food & Snacks",
    location: "College Gate",
    description: "Open:10 AM-10 PM.",
    rating: 3.9,
    menu: [
      { id: "item-101", name: "চিকেন ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-102", name: "ক্রিস্পি চিকেন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-103", name: "চিকেন উইংস (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-104", name: "ফ্রাইড রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-105", name: "চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-106", name: "স্পেশাল চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-107", name: "স্পেশাল ফ্রাইড রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 400, available: true },
      { id: "item-108", name: "বিফ রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-109", name: "প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-110", name: "চিকেন & প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-111", name: "চিকেন সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-112", name: "বিফ সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-113", name: "বিফ কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-114", name: "চিকেন কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-115", name: "চিকেন ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-116", name: "ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-117", name: "বিফ চিলি ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-118", name: "চিকেন পিজ্জা ৬\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 260, available: true },
      { id: "item-119", name: "চিকেন পিজ্জা ৯\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-120", name: "বিফ পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-121", name: "প্রন পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-122", name: "চাওমিন (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-123", name: "থাই নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-124", name: "নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-125", name: "চিকেন নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-126", name: "স্পেশাল নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-127", name: "থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-128", name: "চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-129", name: "চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-130", name: "চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-131", name: "ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-132", name: "স্প্রিং রোল (৮ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-133", name: "চিকেন অনথন (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-134", name: "ক্রিস্পি বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-135", name: "চিকেন চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-136", name: "বিফ সাব চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-137", name: "চিকেন বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-138", name: "বিফ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-139", name: "বিফ চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-140", name: "চিকেন লেগ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-141", name: "চিকেন স্পেশাল বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-142", name: "নাগা বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-143", name: "সাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-144", name: "সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-145", name: "বিফ সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-146", name: "ক্লাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-147", name: "চিকেন স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-148", name: "চিকেন ললিপপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-149", name: "চিকেন ড্রাম স্টিক (২ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-150", name: "পাস্তা (রেড সস) (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-151", name: "পাস্তা উইথ চিজ (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-152", name: "চিংড়ি ফ্রাই (১০ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-153", name: "আমেরিকান চপসি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 380, available: true },
      { id: "item-154", name: "চিকেন চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-155", name: "প্রন চিলি অনিয়ন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-156", name: "বিফ চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-157", name: "চিকেন সাব বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-158", name: "চিকেন মিট বল (৪ স্টিক)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-159", name: "ফ্রেঞ্চ ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-160", name: "মিল্ক শেক", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-161", name: "মুঠি কাবাব", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-162", name: "চিকেন চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-163", name: "বিফ চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-164", name: "চিকেন নাগেট (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-165", name: "চিকেন ক্যাসোনাট সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-166", name: "গ্রিন সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-167", name: "ফ্রেশ জুস (সিজনাল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-168", name: "কোল্ড কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-169", name: "লাচ্ছি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-170", name: "কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-171", name: "পানি (৫০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },
      { id: "item-172", name: "কোল্ড ড্রিংস (ওয়ান টাইম গ্লাস ২০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },

      { id: "item-173", name: "প্যাকেজ ০১: ফ্রাইড রাইস + ভেজিটেবল কারি + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০১ (১:১)", price: 220, available: true },
      { id: "item-174", name: "প্যাকেজ ০২: ফ্রাইড রাইস + চিকেন কারি + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০২ (১:১)", price: 270, available: true },
      { id: "item-175", name: "প্যাকেজ ০৩: চিকেন রাইস + চিকেন ফ্রাই (৪ পিস) + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৩ (১:১)", price: 290, available: true },
      { id: "item-176", name: "প্যাকেজ ০৪: ফ্রাইড রাইস + বিফ চিলি ফ্রাই + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৪ (১:১)", price: 380, available: true },
      { id: "item-177", name: "প্যাকেজ ০৫: চিকেন রাইস + মিনি চিকেন + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৫ (১:১)", price: 250, available: true },
      { id: "item-178", name: "প্যাকেজ ০৬: চিকেন রাইস + চিকেন ফ্রাই + ভেজিটেবল + থাই স্যুপ/চিকেন স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৬ (১:১)", price: 380, available: true },
      { id: "item-179", name: "প্যাকেজ ০৭: থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-180", name: "প্যাকেজ ০৭: চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-181", name: "প্যাকেজ ০৭: ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-182", name: "প্যাকেজ ০৭: চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-183", name: "প্যাকেজ ০৭: চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-184", name: "প্যাকেজ ০৮: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + থাই স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৮ (১:২)", price: 720, available: true },
      { id: "item-185", name: "প্যাকেজ ০৯: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + কোক + থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৯ (১:৪)", price: 1600, available: true },
      { id: "item-186", name: "প্যাকেজ ১০: চিজ বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১০ (১:১)", price: 300, available: true },
      { id: "item-187", name: "প্যাকেজ ১১: চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১১ (১:১)", price: 180, available: true },
      { id: "item-188", name: "প্যাকেজ ১২: বিফ/চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১২ (১:১)", price: 280, available: true },
      { id: "item-189", name: "প্যাকেজ ১৩: চিকেন চাওমিন + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৩ (১:১)", price: 290, available: true },
      { id: "item-190", name: "প্যাকেজ ১৪: স্যুপ + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৪ (১:১)", price: 250, available: true },
      { id: "item-191", name: "প্যাকেজ ১৫: ফ্রাইড রাইস + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৫ (১:১)", price: 220, available: true },
      { id: "item-192", name: "প্যাকেজ ১৬: থাই স্যুপ + ওয়ানটন (০২ পিস) + চিকেন ফ্রাই (০২ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৬ (১:১)", price: 280, available: true }
    ]
  },

  {
    id: "rest-005",
    name: "Bismillah Mini Chinese and Fast Food",
    image: "assets/restaurants/college_gate_cafe.jpg",
    category: "Fast Food & Snacks",
    location: "College Gate",
    description: "Open:10 AM-10 PM.",
    rating: 3.9,
    menu: [
      { id: "item-101", name: "চিকেন ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-102", name: "ক্রিস্পি চিকেন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-103", name: "চিকেন উইংস (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-104", name: "ফ্রাইড রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-105", name: "চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-106", name: "স্পেশাল চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-107", name: "স্পেশাল ফ্রাইড রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 400, available: true },
      { id: "item-108", name: "বিফ রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-109", name: "প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-110", name: "চিকেন & প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-111", name: "চিকেন সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-112", name: "বিফ সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-113", name: "বিফ কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-114", name: "চিকেন কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-115", name: "চিকেন ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-116", name: "ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-117", name: "বিফ চিলি ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-118", name: "চিকেন পিজ্জা ৬\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 260, available: true },
      { id: "item-119", name: "চিকেন পিজ্জা ৯\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-120", name: "বিফ পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-121", name: "প্রন পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-122", name: "চাওমিন (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-123", name: "থাই নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-124", name: "নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-125", name: "চিকেন নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-126", name: "স্পেশাল নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-127", name: "থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-128", name: "চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-129", name: "চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-130", name: "চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-131", name: "ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-132", name: "স্প্রিং রোল (৮ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-133", name: "চিকেন অনথন (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-134", name: "ক্রিস্পি বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-135", name: "চিকেন চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-136", name: "বিফ সাব চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-137", name: "চিকেন বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-138", name: "বিফ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-139", name: "বিফ চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-140", name: "চিকেন লেগ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-141", name: "চিকেন স্পেশাল বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-142", name: "নাগা বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-143", name: "সাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-144", name: "সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-145", name: "বিফ সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-146", name: "ক্লাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-147", name: "চিকেন স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-148", name: "চিকেন ললিপপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-149", name: "চিকেন ড্রাম স্টিক (২ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-150", name: "পাস্তা (রেড সস) (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-151", name: "পাস্তা উইথ চিজ (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-152", name: "চিংড়ি ফ্রাই (১০ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-153", name: "আমেরিকান চপসি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 380, available: true },
      { id: "item-154", name: "চিকেন চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-155", name: "প্রন চিলি অনিয়ন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-156", name: "বিফ চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-157", name: "চিকেন সাব বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-158", name: "চিকেন মিট বল (৪ স্টিক)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-159", name: "ফ্রেঞ্চ ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-160", name: "মিল্ক শেক", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-161", name: "মুঠি কাবাব", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-162", name: "চিকেন চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-163", name: "বিফ চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-164", name: "চিকেন নাগেট (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-165", name: "চিকেন ক্যাসোনাট সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-166", name: "গ্রিন সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-167", name: "ফ্রেশ জুস (সিজনাল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-168", name: "কোল্ড কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-169", name: "লাচ্ছি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-170", name: "কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-171", name: "পানি (৫০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },
      { id: "item-172", name: "কোল্ড ড্রিংস (ওয়ান টাইম গ্লাস ২০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },

      { id: "item-173", name: "প্যাকেজ ০১: ফ্রাইড রাইস + ভেজিটেবল কারি + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০১ (১:১)", price: 220, available: true },
      { id: "item-174", name: "প্যাকেজ ০২: ফ্রাইড রাইস + চিকেন কারি + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০২ (১:১)", price: 270, available: true },
      { id: "item-175", name: "প্যাকেজ ০৩: চিকেন রাইস + চিকেন ফ্রাই (৪ পিস) + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৩ (১:১)", price: 290, available: true },
      { id: "item-176", name: "প্যাকেজ ০৪: ফ্রাইড রাইস + বিফ চিলি ফ্রাই + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৪ (১:১)", price: 380, available: true },
      { id: "item-177", name: "প্যাকেজ ০৫: চিকেন রাইস + মিনি চিকেন + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৫ (১:১)", price: 250, available: true },
      { id: "item-178", name: "প্যাকেজ ০৬: চিকেন রাইস + চিকেন ফ্রাই + ভেজিটেবল + থাই স্যুপ/চিকেন স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৬ (১:১)", price: 380, available: true },
      { id: "item-179", name: "প্যাকেজ ০৭: থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-180", name: "প্যাকেজ ০৭: চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-181", name: "প্যাকেজ ০৭: ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-182", name: "প্যাকেজ ০৭: চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-183", name: "প্যাকেজ ০৭: চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-184", name: "প্যাকেজ ০৮: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + থাই স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৮ (১:২)", price: 720, available: true },
      { id: "item-185", name: "প্যাকেজ ০৯: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + কোক + থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৯ (১:৪)", price: 1600, available: true },
      { id: "item-186", name: "প্যাকেজ ১০: চিজ বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১০ (১:১)", price: 300, available: true },
      { id: "item-187", name: "প্যাকেজ ১১: চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১১ (১:১)", price: 180, available: true },
      { id: "item-188", name: "প্যাকেজ ১২: বিফ/চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১২ (১:১)", price: 280, available: true },
      { id: "item-189", name: "প্যাকেজ ১৩: চিকেন চাওমিন + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৩ (১:১)", price: 290, available: true },
      { id: "item-190", name: "প্যাকেজ ১৪: স্যুপ + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৪ (১:১)", price: 250, available: true },
      { id: "item-191", name: "প্যাকেজ ১৫: ফ্রাইড রাইস + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৫ (১:১)", price: 220, available: true },
      { id: "item-192", name: "প্যাকেজ ১৬: থাই স্যুপ + ওয়ানটন (০২ পিস) + চিকেন ফ্রাই (০২ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৬ (১:১)", price: 280, available: true }
    ]
  },

  {
    id: "rest-005",
    name: "Bismillah Mini Chinese and Fast Food",
    image: "assets/restaurants/college_gate_cafe.jpg",
    category: "Fast Food & Snacks",
    location: "College Gate",
    description: "Open:10 AM-10 PM.",
    rating: 3.9,
    menu: [
      { id: "item-101", name: "চিকেন ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-102", name: "ক্রিস্পি চিকেন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-103", name: "চিকেন উইংস (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-104", name: "ফ্রাইড রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-105", name: "চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-106", name: "স্পেশাল চিকেন রাইস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-107", name: "স্পেশাল ফ্রাইড রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 400, available: true },
      { id: "item-108", name: "বিফ রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-109", name: "প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-110", name: "চিকেন & প্রন রাইস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-111", name: "চিকেন সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-112", name: "বিফ সাসলিগ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-113", name: "বিফ কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-114", name: "চিকেন কারি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-115", name: "চিকেন ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-116", name: "ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-117", name: "বিফ চিলি ভেজিটেবল", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-118", name: "চিকেন পিজ্জা ৬\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 260, available: true },
      { id: "item-119", name: "চিকেন পিজ্জা ৯\"", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-120", name: "বিফ পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-121", name: "প্রন পিজ্জা", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 780, available: true },
      { id: "item-122", name: "চাওমিন (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-123", name: "থাই নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-124", name: "নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-125", name: "চিকেন নুডুলস", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-126", name: "স্পেশাল নুডুলস (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-127", name: "থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-128", name: "চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 130, available: true },
      { id: "item-129", name: "চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-130", name: "চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-131", name: "ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 150, available: true },
      { id: "item-132", name: "স্প্রিং রোল (৮ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 350, available: true },
      { id: "item-133", name: "চিকেন অনথন (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-134", name: "ক্রিস্পি বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-135", name: "চিকেন চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-136", name: "বিফ সাব চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-137", name: "চিকেন বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-138", name: "বিফ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-139", name: "বিফ চিজ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-140", name: "চিকেন লেগ বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-141", name: "চিকেন স্পেশাল বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-142", name: "নাগা বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-143", name: "সাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-144", name: "সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 220, available: true },
      { id: "item-145", name: "বিফ সাব চিজ স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-146", name: "ক্লাব স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-147", name: "চিকেন স্যান্ডউইচ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-148", name: "চিকেন ললিপপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-149", name: "চিকেন ড্রাম স্টিক (২ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-150", name: "পাস্তা (রেড সস) (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 280, available: true },
      { id: "item-151", name: "পাস্তা উইথ চিজ (১:২)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 800, available: true },
      { id: "item-152", name: "চিংড়ি ফ্রাই (১০ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-153", name: "আমেরিকান চপসি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 380, available: true },
      { id: "item-154", name: "চিকেন চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 450, available: true },
      { id: "item-155", name: "প্রন চিলি অনিয়ন", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 500, available: true },
      { id: "item-156", name: "বিফ চিলি ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 550, available: true },
      { id: "item-157", name: "চিকেন সাব বার্গার", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-158", name: "চিকেন মিট বল (৪ স্টিক)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 200, available: true },
      { id: "item-159", name: "ফ্রেঞ্চ ফ্রাই", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-160", name: "মিল্ক শেক", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 160, available: true },
      { id: "item-161", name: "মুঠি কাবাব", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-162", name: "চিকেন চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 250, available: true },
      { id: "item-163", name: "বিফ চপ (৪ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 300, available: true },
      { id: "item-164", name: "চিকেন নাগেট (৬ পিস)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-165", name: "চিকেন ক্যাসোনাট সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 600, available: true },
      { id: "item-166", name: "গ্রিন সালাদ", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-167", name: "ফ্রেশ জুস (সিজনাল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 190, available: true },
      { id: "item-168", name: "কোল্ড কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 180, available: true },
      { id: "item-169", name: "লাচ্ছি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 120, available: true },
      { id: "item-170", name: "কফি", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 100, available: true },
      { id: "item-171", name: "পানি (৫০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },
      { id: "item-172", name: "কোল্ড ড্রিংস (ওয়ান টাইম গ্লাস ২০০ এম.এল)", image: "assets/food/chicken_burger.jpg", category: "Regular Menu", description: "", price: 20, available: true },

      { id: "item-173", name: "প্যাকেজ ০১: ফ্রাইড রাইস + ভেজিটেবল কারি + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০১ (১:১)", price: 220, available: true },
      { id: "item-174", name: "প্যাকেজ ০২: ফ্রাইড রাইস + চিকেন কারি + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০২ (১:১)", price: 270, available: true },
      { id: "item-175", name: "প্যাকেজ ০৩: চিকেন রাইস + চিকেন ফ্রাই (৪ পিস) + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৩ (১:১)", price: 290, available: true },
      { id: "item-176", name: "প্যাকেজ ০৪: ফ্রাইড রাইস + বিফ চিলি ফ্রাই + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৪ (১:১)", price: 380, available: true },
      { id: "item-177", name: "প্যাকেজ ০৫: চিকেন রাইস + মিনি চিকেন + ভেজিটেবল + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৫ (১:১)", price: 250, available: true },
      { id: "item-178", name: "প্যাকেজ ০৬: চিকেন রাইস + চিকেন ফ্রাই + ভেজিটেবল + থাই স্যুপ/চিকেন স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৬ (১:১)", price: 380, available: true },
      { id: "item-179", name: "প্যাকেজ ০৭: থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-180", name: "প্যাকেজ ০৭: চিকেন স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-181", name: "প্যাকেজ ০৭: ফ্রেশ ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৪৮০ টাকা", price: 480, available: true },
      { id: "item-182", name: "প্যাকেজ ০৭: চিকেন ভেজিটেবল স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-183", name: "প্যাকেজ ০৭: চিকেন কর্ণ স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৭ (১:৪) — মেনু কার্ডে মূল্য ৫৮০ টাকা", price: 580, available: true },
      { id: "item-184", name: "প্যাকেজ ০৮: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + থাই স্যুপ + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৮ (১:২)", price: 720, available: true },
      { id: "item-185", name: "প্যাকেজ ০৯: ফ্রাইড রাইস + চিকেন ফ্রাই + চিকেন ভেজিটেবল + কোক + থাই স্যুপ", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ০৯ (১:৪)", price: 1600, available: true },
      { id: "item-186", name: "প্যাকেজ ১০: চিজ বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১০ (১:১)", price: 300, available: true },
      { id: "item-187", name: "প্যাকেজ ১১: চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১১ (১:১)", price: 180, available: true },
      { id: "item-188", name: "প্যাকেজ ১২: বিফ/চিকেন বার্গার + ফ্রেঞ্চ ফ্রাই + চিকেন ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১২ (১:১)", price: 280, available: true },
      { id: "item-189", name: "প্যাকেজ ১৩: চিকেন চাওমিন + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৩ (১:১)", price: 290, available: true },
      { id: "item-190", name: "প্যাকেজ ১৪: স্যুপ + চিকেন ফ্রাই (৪ পিস) + ফ্রেঞ্চ ফ্রাই + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৪ (১:১)", price: 250, available: true },
      { id: "item-191", name: "প্যাকেজ ১৫: ফ্রাইড রাইস + চিকেন ফ্রাই (৪ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৫ (১:১)", price: 220, available: true },
      { id: "item-192", name: "প্যাকেজ ১৬: থাই স্যুপ + ওয়ানটন (০২ পিস) + চিকেন ফ্রাই (০২ পিস) + কোক", image: "assets/food/chicken_burger.jpg", category: "Package Menu", description: "প্যাকেজ ১৬ (১:১)", price: 280, available: true }
    ]
  }
  
];

